"""Ajout champ image_url à supplements et choice_options

Revision ID: a296d9936608
Revises: 67cb912bbfdc
Create Date: 2025-08-06 10:52:44.990915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a296d9936608'
down_revision = '67cb912bbfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.add_column('choice_options', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('menus', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('options', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('options', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('options', sa.Column('type', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'options', ['slug'])
    op.drop_constraint(op.f('options_product_id_fkey'), 'options', type_='foreignkey')
    op.drop_column('options', 'product_id')
    op.add_column('order_items', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'menus', ['menu_id'], ['id'])
    op.add_column('products', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'products', ['slug'])
    op.add_column('supplements', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplements', 'image_url')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'slug')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'menu_id')
    op.add_column('options', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('options_product_id_fkey'), 'options', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'options', type_='unique')
    op.drop_column('options', 'type')
    op.drop_column('options', 'slug')
    op.drop_column('options', 'image_url')
    op.drop_column('menus', 'image_url')
    op.drop_column('choice_options', 'image_url')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###

